# Generated by Django 6.0.4 on 2026-04-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('triggered_by', models.CharField(blank=True, default='admin', max_length=255)),
                ('document_content', models.TextField(blank=True)),
                ('postman_content', models.TextField(blank=True)),
                ('generated_config', models.TextField(blank=True)),
                ('code_changes', models.TextField(blank=True)),
                ('agent_response', models.TextField(blank=True)),
                ('pr_url', models.URLField(blank=True)),
                ('branch_name', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
